[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi",
    "uvicorn",
    "python-dotenv",
    "langchain",
    "langchain-community",
    "langchain-groq",
    "langchain-huggingface",
    "sentence-transformers",
    "docx2txt",
    "pypdf",
    "python-multipart",
    "pytest",
    "httpx",
    "langchain-chroma",
]
